// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const hikes = [
  {
    "timestamp": "2026-08-29 00:39:43",
    "id": "32krun",
    "title": "32km Czechlauf",
    "description": "Die einzige Möglichkeit, in dieser Gegend eine flache Strecke zu laufen, ist entlang der Elbe. Glücklicherweise führt der Elberadweg an Bad Schandau vorbei bis nach Tschechien. Ich werde 16 Kilometer flussabwärts  in die Tschechische Republik laufen und dann wieder zurückkehren, insgesamt also 32 km. Das ist ein gutes Training für den Marathon in Dijon, der nach demselben Prinzip abläuft: bis zu einem bestimmten Punkt laufen, umkehren und zurücklaufen.",
    "image": "32krun.jpg"
  }
];
