// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const notes = [
  {
    "id": "u6vx2r",
    "body": "Google Earth App",
    "indent": 0
  },
  {
    "id": "lcj4ke",
    "body": "[KMZ Datei](https://tanguay.info/badsch/download/badsch001.kmz)",
    "indent": 1
  },
  {
    "id": "5r7nbb",
    "body": "Plan",
    "indent": 0
  },
  {
    "id": "uzsgmi",
    "body": "Sonntag 30",
    "indent": 1
  },
  {
    "id": "6m3dyf",
    "body": "07:37 Berlin Südkreuz",
    "indent": 2
  },
  {
    "id": "r4mhis",
    "body": "09:35 Bad Schandau",
    "indent": 2
  },
  {
    "id": "qu1qgk",
    "body": "Fähre F5, alle 30 Minuten, 2,00 €",
    "indent": 3
  },
  {
    "id": "rs3wox",
    "body": "WANDERUNG: Casper-David-Friedrich-Weg",
    "indent": 2
  },
  {
    "id": "z05300",
    "body": "Montag 31",
    "indent": 1
  },
  {
    "id": "ua4x9r",
    "body": "Wetter: eher Regen",
    "indent": 2
  },
  {
    "id": "qsnajj",
    "body": "05:00 32K Czechlauf",
    "indent": 2
  },
  {
    "id": "69mymq",
    "body": "WANDERUNG: Königsstein",
    "indent": 2
  },
  {
    "id": "in76sp",
    "body": "Dienstag 1",
    "indent": 1
  },
  {
    "id": "wchn71",
    "body": "WANDERUNG: Kuhstall (20km)",
    "indent": 2
  },
  {
    "id": "fce6rj",
    "body": "Mittwoch 2",
    "indent": 1
  },
  {
    "id": "l8hks3",
    "body": "11:44 Bad Schandau",
    "indent": 2
  },
  {
    "id": "xf591j",
    "body": "12:28 Dresden ankommen",
    "indent": 2
  },
  {
    "id": "2tfk8m",
    "body": "16:33 Dresden losfahren",
    "indent": 2
  },
  {
    "id": "u1wrfg",
    "body": "18:20 Südkreuz",
    "indent": 2
  },
  {
    "id": "w3rkt3",
    "body": "Wanderungen",
    "indent": 0
  },
  {
    "id": "dc0bkk",
    "body": "https://www.komoot.com/discover/Bad_Schandau/@50.9247388,14.2153046/tours?sport=hike&map=true&max_distance=9000&pageNumber=1",
    "indent": 1
  },
  {
    "id": "pkqriw",
    "body": "https://www.komoot.com/de-de/guide/2051/wandern-rund-um-bad-schandau",
    "indent": 1
  },
  {
    "id": "droguq",
    "body": "Czech run",
    "indent": 0
  },
  {
    "id": "01socm",
    "body": "Dresden itinerary",
    "indent": 0
  },
  {
    "id": "pfsdpj",
    "body": "Bad Schandau",
    "indent": 0
  },
  {
    "id": "ztt6fh",
    "body": "mögliche Orte",
    "indent": 0
  },
  {
    "id": "8r3a70",
    "body": "Königsstein",
    "indent": 1
  },
  {
    "id": "bf0don",
    "body": "Kuhstall",
    "indent": 1
  },
  {
    "id": "9icxrk",
    "body": "mögliche Aktivitäten",
    "indent": 0
  },
  {
    "id": "a1o9d0",
    "body": "Boot",
    "indent": 1
  },
  {
    "id": "e4hg5i",
    "body": "Busse",
    "indent": 0
  },
  {
    "id": "hzeeb5",
    "body": "https://grok.com/c/05cf54de-5b0b-412b-8629-cf1dade3df1d?rid=5fb41d2d-83dd-4445-bd42-50765114093f",
    "indent": 1
  }
];
