// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const notes = [
  {
    "id": "k1iq4e",
    "body": "Plan",
    "indent": 0
  },
  {
    "id": "zwm84s",
    "body": "Sonntag 30",
    "indent": 1
  },
  {
    "id": "7872ix",
    "body": "07:37 Berlin Südkreuz",
    "indent": 2
  },
  {
    "id": "lzgprf",
    "body": "09:35 Bad Schandau",
    "indent": 2
  },
  {
    "id": "sw4fxe",
    "body": "Fähre F5, alle 30 Minuten, 2,00 €",
    "indent": 3
  },
  {
    "id": "r5wpzr",
    "body": "WANDERUNG: Casper-David-Friedrich-Weg",
    "indent": 2
  },
  {
    "id": "u7cucc",
    "body": "Montag 31",
    "indent": 1
  },
  {
    "id": "ocrsuh",
    "body": "Wetter: eher Regen",
    "indent": 2
  },
  {
    "id": "qf2bvd",
    "body": "05:00 32K Czechlauf",
    "indent": 2
  },
  {
    "id": "azjj5t",
    "body": "WANDERUNG: Königsstein",
    "indent": 2
  },
  {
    "id": "auqcg8",
    "body": "Dienstag 1",
    "indent": 1
  },
  {
    "id": "9idy48",
    "body": "WANDERUNG: Kuhstall (20km)",
    "indent": 2
  },
  {
    "id": "qz5umi",
    "body": "Mittwoch 2",
    "indent": 1
  },
  {
    "id": "2h8ch1",
    "body": "11:44 Bad Schandau",
    "indent": 2
  },
  {
    "id": "af8i6r",
    "body": "12:28 Dresden ankommen",
    "indent": 2
  },
  {
    "id": "axzo2p",
    "body": "16:33 Dresden losfahren",
    "indent": 2
  },
  {
    "id": "hrly72",
    "body": "18:20 Südkreuz",
    "indent": 2
  },
  {
    "id": "2pglld",
    "body": "Wanderungen",
    "indent": 0
  },
  {
    "id": "oys3z2",
    "body": "https://www.komoot.com/discover/Bad_Schandau/@50.9247388,14.2153046/tours?sport=hike&map=true&max_distance=9000&pageNumber=1",
    "indent": 1
  },
  {
    "id": "74owfi",
    "body": "https://www.komoot.com/de-de/guide/2051/wandern-rund-um-bad-schandau",
    "indent": 1
  },
  {
    "id": "9z6dpz",
    "body": "Czech run",
    "indent": 0
  },
  {
    "id": "9bh6t2",
    "body": "Dresden itinerary",
    "indent": 0
  },
  {
    "id": "i4sq9b",
    "body": "Bad Schandau",
    "indent": 0
  },
  {
    "id": "m2nqsm",
    "body": "mögliche Orte",
    "indent": 0
  },
  {
    "id": "yce779",
    "body": "Königsstein",
    "indent": 1
  },
  {
    "id": "6o8vdi",
    "body": "Kuhstall",
    "indent": 1
  },
  {
    "id": "2zibsy",
    "body": "mögliche Aktivitäten",
    "indent": 0
  },
  {
    "id": "s58d3g",
    "body": "Boot",
    "indent": 1
  },
  {
    "id": "f5rpm1",
    "body": "Busse",
    "indent": 0
  },
  {
    "id": "dqbmky",
    "body": "https://grok.com/c/05cf54de-5b0b-412b-8629-cf1dade3df1d?rid=5fb41d2d-83dd-4445-bd42-50765114093f",
    "indent": 1
  }
];
