// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const notes = [
  {
    "id": "wwlype",
    "body": "Google Earth App",
    "indent": 0
  },
  {
    "id": "xzd71a",
    "body": "[KMZ Datei](https://tanguay.info/badsch/download/badsch003.kmz)",
    "indent": 1
  },
  {
    "id": "co90x2",
    "body": "Plan",
    "indent": 0
  },
  {
    "id": "cmwn41",
    "body": "Sonntag 30",
    "indent": 1
  },
  {
    "id": "73a20i",
    "body": "07:37 Berlin Südkreuz",
    "indent": 2
  },
  {
    "id": "k1f98y",
    "body": "09:35 Bad Schandau",
    "indent": 2
  },
  {
    "id": "mv9ber",
    "body": "Fähre F5, alle 30 Minuten, 2,00 €",
    "indent": 3
  },
  {
    "id": "loulko",
    "body": "**WANDERUNG: Casper-David-Friedrich-Weg (15km)**",
    "indent": 2
  },
  {
    "id": "uqqf5i",
    "body": "STATION 1:",
    "indent": 3,
    "image": "friedstat1.jpg"
  },
  {
    "id": "42hoc9",
    "body": "STATION 2: Das Steinbruchmotiverster Pfad von \"Zum Mittelhangweg\" in die Berge",
    "indent": 3,
    "image": "thefirstup.jpg"
  },
  {
    "id": "61nn5a",
    "body": "das Steinbruchmotiv Schild",
    "indent": 3,
    "image": "steingbruhmosign.jpg"
  },
  {
    "id": "9ufs72",
    "body": "*\"Das sind die sportlichen Abschnitte des Weges am Anfang hinter Krippen und dann bei Schmilka hoch nach Schona, aber es lohnt sich\"*",
    "indent": 3,
    "image": "upthestepsss.jpg"
  },
  {
    "id": "xpsut4",
    "body": "*\"Der MittelhangWeg zwischen Krippen und Hirschgrund ist nichts für Touries mit Kindern und ungeeignetem Schuhwerk! Der Weg ist größtenteils nur Schulterbreit manchmal nur 2 Fuß und gespickt mit möglichen Abrutschstellen den steilen Hang hinunter. Bei Gegenverkehr kann es eng werden, vor allem in der Saison bei vielen Wanderern.\"*",
    "indent": 3,
    "image": "narropath.jpg"
  },
  {
    "id": "9dfbca",
    "body": "Aussichtspunkt Burg Schöna",
    "indent": 3,
    "image": "schona.jpg"
  },
  {
    "id": "6w9rkv",
    "body": "Montag 31",
    "indent": 1
  },
  {
    "id": "yo4w3f",
    "body": "Wetter: eher Regen",
    "indent": 2
  },
  {
    "id": "8qyvzp",
    "body": "**WANDERUNG: Elberadweg bis Königsstein und zurück (18km)**",
    "indent": 2
  },
  {
    "id": "1j8j0i",
    "body": "hier beginnt der Elberadweg",
    "indent": 3,
    "image": "getelbrad.jpg"
  },
  {
    "id": "c6w7m7",
    "body": "Königstein in der Ferne von der Elbe aus gesehen",
    "indent": 3,
    "image": "approchinkoen.jpg"
  },
  {
    "id": "khkiqx",
    "body": "Blick auf die Festung Königstein",
    "indent": 3,
    "image": "uptodko.jpg"
  },
  {
    "id": "aybjy9",
    "body": "Patrouillenweg",
    "indent": 3,
    "image": "uptoko.jpg"
  },
  {
    "id": "ui6drj",
    "body": "Dienstag 1",
    "indent": 1
  },
  {
    "id": "amh7p3",
    "body": "05:00 32K Czechlauf",
    "indent": 2
  },
  {
    "id": "789a3e",
    "body": "**WANDERUNG: Kuhstall (4km)**",
    "indent": 2
  },
  {
    "id": "2qqxxf",
    "body": "am einfachsten nimmst du von Bad Schandau, Kurpark",
    "indent": 3,
    "image": "startbahn.jpg"
  },
  {
    "id": "ej88jw",
    "body": "die historische Kirnitzschtalbahn",
    "indent": 3,
    "image": "firstbahn.jpg"
  },
  {
    "id": "ncggby",
    "body": "sie ist keine Buslinie, sondern eine Straßenbahn, fährt direkt durch das Kirnitzschtal und braucht etwa 30–35 Minuten. Im Sommerfahrplan fährt sie täglich in der Regel alle 30 Minuten",
    "indent": 3
  },
  {
    "id": "uv0h98",
    "body": "bis zur Endhaltestelle \"Lichtenhainer Wasserfall\"",
    "indent": 3,
    "image": "startpunktkuh.jpg"
  },
  {
    "id": "q6o38s",
    "body": "Bushaltestelle Lichtenhainer Wasserfall",
    "indent": 3
  },
  {
    "id": "k6w8qm",
    "body": "Wanderungstartpunkt",
    "indent": 3,
    "image": "whertostart.jpg"
  },
  {
    "id": "rb9dyd",
    "body": "Brücke über den Münzbornbach",
    "indent": 3,
    "image": "brucke.jpg"
  },
  {
    "id": "dmju0m",
    "body": "historischer Wegweiser",
    "indent": 3,
    "image": "signto.jpg"
  },
  {
    "id": "o36evy",
    "body": "Märchenhafter Treppenaufstieg",
    "indent": 3,
    "image": "tehsteps.jpg"
  },
  {
    "id": "pkwxgt",
    "body": "Kuhstall Felsentor",
    "indent": 3,
    "image": "kuhstallFelsentor.jpg"
  },
  {
    "id": "n9x9m3",
    "body": "Königliche Brücke über die Kirnitzsch",
    "indent": 3,
    "image": "burckover.jpg"
  },
  {
    "id": "so50wt",
    "body": "nimm von hier die Kirnitzschtalbahn zurück nach Bad Schandau",
    "indent": 3,
    "image": "strassback.jpg"
  },
  {
    "id": "9l2smu",
    "body": "Mittwoch 2",
    "indent": 1
  },
  {
    "id": "l3jtkb",
    "body": "11:44 Bad Schandau",
    "indent": 2
  },
  {
    "id": "lowxah",
    "body": "12:28 Dresden ankommen",
    "indent": 2
  },
  {
    "id": "m1gxm1",
    "body": "16:33 Dresden losfahren",
    "indent": 2
  },
  {
    "id": "c9umkk",
    "body": "18:20 Südkreuz",
    "indent": 2
  },
  {
    "id": "fo1rf0",
    "body": "Wanderungen",
    "indent": 0
  },
  {
    "id": "8r7zcu",
    "body": "https://www.komoot.com/discover/Bad_Schandau/@50.9247388,14.2153046/tours?sport=hike&map=true&max_distance=9000&pageNumber=1",
    "indent": 1
  },
  {
    "id": "xuprjv",
    "body": "https://www.komoot.com/de-de/guide/2051/wandern-rund-um-bad-schandau",
    "indent": 1
  },
  {
    "id": "9yugh4",
    "body": "Czech run",
    "indent": 0
  },
  {
    "id": "iqn3d8",
    "body": "Dresden itinerary",
    "indent": 0
  },
  {
    "id": "smbyxh",
    "body": "Bad Schandau",
    "indent": 0
  },
  {
    "id": "jqh0vd",
    "body": "mögliche Orte",
    "indent": 0
  },
  {
    "id": "8ympd5",
    "body": "Königsstein",
    "indent": 1
  },
  {
    "id": "j2dlmi",
    "body": "Kuhstall",
    "indent": 1
  },
  {
    "id": "03dur5",
    "body": "mögliche Aktivitäten",
    "indent": 0
  },
  {
    "id": "zprgty",
    "body": "Boot",
    "indent": 1
  },
  {
    "id": "3yqn4o",
    "body": "Busse",
    "indent": 0
  },
  {
    "id": "lznxcm",
    "body": "https://grok.com/c/05cf54de-5b0b-412b-8629-cf1dade3df1d?rid=5fb41d2d-83dd-4445-bd42-50765114093f",
    "indent": 1
  }
];
