import fs from "node:fs";
import path from "node:path";

export interface RetroSection {
  title: string;
  images: string[];
}

export interface ParseRetroOptions {
  inputRelativePath?: string;
  outputRelativePath?: string;
  exportVarName?: string;
}

export function parseRetro(options: ParseRetroOptions = {}): void {
  const inputRelativePath = options.inputRelativePath || "data/retro.dpod.txt";
  const outputRelativePath = options.outputRelativePath || "js/data-parsed/retro.js";
  const exportVarName = options.exportVarName || "retro";

  const rootDir = process.cwd();
  const inputPath = path.resolve(rootDir, inputRelativePath);
  const outputPath = path.resolve(rootDir, outputRelativePath);

  console.log(`[parse-retro] Reading: ${inputRelativePath}`);

  if (!fs.existsSync(inputPath)) {
    console.error(`[parse-retro] Error: Input file not found at ${inputPath}`);
    return;
  }

  const content = fs.readFileSync(inputPath, "utf-8");
  const lines = content.split(/\r?\n/);
  const sections: RetroSection[] = [];
  let currentSection: RetroSection | null = null;
  let totalImages = 0;

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i].trim();
    if (!rawLine || rawLine.startsWith("//") || rawLine.startsWith("#")) {
      continue;
    }

    if (rawLine.toLowerCase().includes(".jpg")) {
      if (!currentSection) {
        currentSection = { title: "", images: [] };
        sections.push(currentSection);
      }
      currentSection.images.push(rawLine);
      totalImages++;
    } else {
      currentSection = { title: rawLine, images: [] };
      sections.push(currentSection);
    }
  }

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const generatedJs = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const ${exportVarName} = ${JSON.stringify(sections, null, 2)};
`;

  fs.writeFileSync(outputPath, generatedJs, "utf-8");
  console.log(
    `[parse-retro] Successfully generated ${outputRelativePath} (${sections.length} sections, ${totalImages} images parsed)`
  );
}

