import fs from "node:fs";
import path from "node:path";

export interface HikeItem {
  timestamp: string;
  id: string;
  title: string;
  description: string;
  image?: string;
}

export interface ParseHikesOptions {
  inputRelativePath?: string;
  outputRelativePath?: string;
  imagesRelativeDir?: string;
  exportVarName?: string;
}

const SUPPORTED_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".gif", ".svg"];

function findImageFile(imagesDir: string, baseId: string): string | undefined {
  if (!fs.existsSync(imagesDir)) {
    return undefined;
  }

  const normalizedTarget = baseId.trim().toLowerCase();
  const dirFiles = fs.readdirSync(imagesDir);

  for (const ext of SUPPORTED_EXTENSIONS) {
    const directCandidate = `${normalizedTarget}${ext}`;
    const directMatch = dirFiles.find((f) => f.toLowerCase() === directCandidate);
    if (directMatch) {
      return directMatch;
    }
  }

  // Also check if baseId already contained an extension
  const rawMatch = dirFiles.find((f) => f.toLowerCase() === normalizedTarget);
  if (rawMatch) {
    return rawMatch;
  }

  return undefined;
}

export function parseHikes(options: ParseHikesOptions = {}): void {
  const inputRelativePath = options.inputRelativePath || "data/hikes.dpod.txt";
  const outputRelativePath = options.outputRelativePath || "js/data-parsed/hikes.js";
  const imagesRelativeDir = options.imagesRelativeDir || "images/hikes";
  const exportVarName = options.exportVarName || "hikes";

  const rootDir = process.cwd();
  const inputPath = path.resolve(rootDir, inputRelativePath);
  const outputPath = path.resolve(rootDir, outputRelativePath);
  const imagesDir = path.resolve(rootDir, imagesRelativeDir);

  console.log(`[parse-hikes] Reading: ${inputRelativePath}`);

  if (!fs.existsSync(inputPath)) {
    console.error(`[parse-hikes] Error: Input file not found at ${inputPath}`);
    return;
  }

  const content = fs.readFileSync(inputPath, "utf-8");
  const lines = content.split(/\r?\n/);
  const hikes: HikeItem[] = [];

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i].trim();
    if (!rawLine || rawLine.startsWith("//") || rawLine.startsWith("#")) {
      continue;
    }

    const parts = rawLine.split(";").map((p) => p.trim());
    if (parts.length < 4) {
      console.warn(`[parse-hikes] Skipping invalid line ${i + 1}: "${rawLine}" (expected at least 4 semicolon-delimited fields)`);
      continue;
    }

    const [timestamp, id, title, ...descParts] = parts;
    const description = descParts.join(";"); // Handle semicolons within description gracefully

    const imageFile = findImageFile(imagesDir, id);

    const hikeItem: HikeItem = {
      timestamp,
      id,
      title,
      description
    };

    if (imageFile) {
      hikeItem.image = imageFile;
    } else {
      console.warn(`[parse-hikes] Warning: No image found in ${imagesRelativeDir} for id "${id}"`);
    }

    hikes.push(hikeItem);
  }

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const generatedJs = `// Auto-generated by cmd/parse-data.ts - DO NOT EDIT MANUALLY
export const ${exportVarName} = ${JSON.stringify(hikes, null, 2)};
`;

  fs.writeFileSync(outputPath, generatedJs, "utf-8");
  console.log(`[parse-hikes] Successfully generated ${outputRelativePath} (${hikes.length} hikes parsed)`);
}
